import { useEffect } from "react";
const imageList = [
  "/assets/contact_img.png",
  "/assets/art.png",
  "/assets/artist.png",
  "/assets/bg_dotted.png",
  "/assets/booked_img.png",
  "/assets/categories_image__.png",
  "/assets/clock.png",
  "/assets/get_art_image.png",
  "/assets/happy_customers.png",
  "/assets/home_main_img.png",
  "/assets/image_art_process.png",
  "/assets/logo.png",
  "/assets/logo_transparent.png",
  "/assets/love_png.png",
  "/assets/paint_dot_1.png",
  "/assets/paintbrush_wcu.png",
  "/assets/photo_frames.png",
  "/assets/premium.png",
  "/assets/arts/afoih.jpg",
  "/assets/arts/blood_art_1.jpg",
  "/assets/arts/blood_art_2.jpg",
  "/assets/arts/blood_art_3.jpg",
  "/assets/arts/blood_art_4.jpg",
  "/assets/arts/blood_art_5.jpg",
  "/assets/arts/blood_art_6.jpg",
  "/assets/arts/blood_art_7.jpg",
  "/assets/arts/blood_art_8.jpg",
  "/assets/arts/blood_art_9.jpg",
  "/assets/arts/blood_art_10.jpg",
  "/assets/arts/blood_art_11.jpg",
  "/assets/arts/blood_art_12.jpg",
  "/assets/arts/blood_art_13.jpg",
  "/assets/arts/blood_art_14.jpg",
  "/assets/arts/blood_art_15.jpg",
  "/assets/arts/blood_art_16.jpg",
  "/assets/arts/blood_art_17.jpg",
  "/assets/arts/blood_art_18.jpg",
  "/assets/arts/blood_art_19.jpg",
  "/assets/arts/blood_art_20.jpg",
  "/assets/arts/blood_art_21.jpg",
  "/assets/arts/blood_art_22.jpg",
  "/assets/arts/blood_art_23.jpg",
  "/assets/arts/blood_art_24.jpg",
  "/assets/arts/blood_art_25.jpg",
  "/assets/arts/blood_art_26.jpg",
  "/assets/arts/blood_art_27.jpg",
  "/assets/arts/blood_art_28.jpg",
  "/assets/arts/blood_art_29.jpg",
  "/assets/arts/blood_art_30.jpg",
  "/assets/arts/blood_art_31.jpg",
  "/assets/arts/blood_art_32.jpg",
  "/assets/arts/blood_art_33.jpg",
  "/assets/arts/blood_art_34.jpg",
  "/assets/arts/blood_art_35.jpg",
  "/assets/arts/digital_art_1.jpg",
  "/assets/arts/digital_art_2.jpg",
  "/assets/arts/digital_art_3.jpg",
  "/assets/arts/digital_art_4.jpg",
  "/assets/arts/digital_art_5.jpg",
  "/assets/arts/digital_art_6.jpg",
  "/assets/arts/imaginary_art_1.jpg",
  "/assets/arts/imaginary_art_2.jpg",
  "/assets/arts/imaginary_art_3.jpg",
  "/assets/arts/IMG-20250819-WA0001.jpg",
  "/assets/arts/IMG-20250819-WA0002.jpg",
  "/assets/arts/IMG-20250819-WA0003.jpg",
  "/assets/arts/IMG-20250819-WA0004.jpg",
  "/assets/arts/IMG-20250819-WA0005.jpg",
  "/assets/arts/IMG-20250819-WA0006.jpg",
  "/assets/arts/IMG-20250819-WA0007.jpg",
  "/assets/arts/IMG-20250819-WA0008.jpg",
  "/assets/arts/IMG-20250819-WA0009.jpg",
  "/assets/arts/IMG-20250820-WA0001.jpg",
  "/assets/arts/IMG-20250820-WA0002.jpg",
  "/assets/arts/IMG-20250820-WA0003.jpg",
  "/assets/arts/IMG-20250820-WA0004.jpg",
  "/assets/arts/IMG-20250820-WA0005.jpg",
  "/assets/arts/IMG-20250820-WA0006.jpg",
  "/assets/arts/pencil_art_1.jpg",
  "/assets/arts/pencil_art_2.jpg",
  "/assets/arts/pencil_art_3.jpg",
  "/assets/arts/pencil_art_4.jpg",
  "/assets/arts/pencil_art_5.jpg",
  "/assets/arts/pencil_art_6.jpg",
  "/assets/arts/pencil_art_7.jpg",
  "/assets/arts/pencil_art_8.jpg",
  "/assets/arts/pencil_art_9.jpg",
  "/assets/arts/recent_arts_1.jpg",
  "/assets/arts/recent_arts_2.jpg",
  "/assets/arts/recent_arts_3.jpg",
  "/assets/arts/recent_arts_4.jpg",
  "/assets/arts/recent_arts_5.jpg",
  "/assets/arts/recent_arts_6.jpg",
];


function PreloadImages() {
  useEffect(() => {
    imageList.forEach((src) => {
      const img = new Image();
      img.src = src;
    });
  }, []);

  return null; // this component doesn’t render anything
}

export default PreloadImages;
